config/routes.rb
Rails.application.routes.draw do
  root to: 'stats#index'
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
  end
  resources :users
  resources :repositories
  resources :members
  resources :groups
end

app/models/group.rb
class Group < ActiveRecord::Base

  has_and_belongs_to_many :members

  has_many :group_permissions
  has_many :repositories, :through => :group_permissions
  
end

app/models/group_permission.rb
class GroupPermission < ActiveRecord::Base

  belongs_to :group
  belongs_to :repository
  
end

app/models/member.rb
class Member < ActiveRecord::Base

  has_and_belongs_to_many :groups

  has_many :member_permissions
  has_many :repositories, :through => :member_permissions
  
end

app/models/member_permission.rb
class MemberPermission < ActiveRecord::Base

  belongs_to :member
  belongs_to :repository
  
end

app/models/repository.rb
class Repository < ActiveRecord::Base

  has_many :member_permissions
  has_many :members, :through => :member_permissions
  has_many :group_permissions
  has_many :groups, :through => :group_permissions
  
  def url
    "https://bitbucket.org/#{owner}/#{slug}"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  
  layout :layout_by_resource

  protected
  def layout_by_resource
    if devise_controller? && resource_name == :user && action_name == "new"
      "login"
    else
      "application"
    end
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.order(:slug)
  end

  def show
    @group = Group.find_by(slug: params[:id])
  end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    @members = Member.order(:name)
  end

  def show
    @member = Member.find_by(username: params[:id])
  end
  
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  def index
    sort = case params['sort']
           when "name" then "slug"
           when "name_reverse" then "slug desc"
           when "date" then "updated_at"
           when "date_reverse" then "updated_at desc"
           else "slug"
           end
    
    @repositories = Repository.order(sort)
  end

  def show
    @repo = Repository.find_by(slug: params[:id])
  end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  
  def index
    @repo_count = Repository.count
    @member_count = Member.count
    @group_count = Group.count
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # use comment out html code server-side
  def comment
  end

  # icon mappers, for easy swapping
  def icon_overview
    "dashboard"
  end

  def icon_repositories
    "code-fork"
  end

  def icon_members
    "user"
  end

  def icon_groups
    "group"
  end

  def icon_expand_sidebar
    "angle-double-right"
  end

  def icon_shrink_sidebar
    "angle-double-left"
  end

  def group_icon(options = {})
    fa_icon(icon_groups, options)
  end

  def member_icon(options = {})
    fa_icon(icon_members, options)
  end

  def repository_icon(options = {})
    fa_icon(icon_repositories, options)
  end
  
end

app/helpers/repository_helper.rb
module RepositoryHelper

  def sort_link_to(text, path, param)
    key = params[:sort] == param ? param + "_reverse" : param
    link_to text, repositories_path(sort: key)
  end
  
end

app/views/groups/index.html.erb
<h3>Groups</h3>

<div class="panel panel-default">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group_path(group.slug) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/show.html.erb
<h3><%= group_icon %> <%= @group.name %></h3>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Members</h3>
  </div>
  <table class="table table-striped">
    <% comment do %>
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <% end %>
    <tbody>
      <% @group.members.sort{ |a,b| a.name <=> b.name }.each do |member| %>
      <tr>
        <td><%= link_to member.name, member_path(member.username) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Repositories</h3>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Permission</th>
      </tr>
    </thead>
    <tbody>
      <% @group.group_permissions.sort{ |a,b| a.repository.name <=> b.repository.name }.each do |perm| %>
      <tr>
        <td><%= link_to perm.repository.name, repository_path(perm.repository.slug) %></td>
        <td width="30%"><%= perm.permission %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header navbar-left">
      <span class="navbar-brand">Bitbucket Browser</span>
    </div>
    <div class="navbar-header navbar-right">
      <ul class="nav navbar-nav" style="overflow: none;">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
            <%= fa_icon "user" %> <%= fa_icon "caret-down" %>
          </a>
          <ul class="dropdown-menu" role="menu">
            <%= render 'layouts/navigation_links' %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <ul class="nav navmenu-nav">
    <li>
      <%= link_to root_path do %>
        <span class="hidden-xs">Overview</span>
        <%= fa_icon icon_overview %>
      <% end %>
    </li>
    <li>
      <%= link_to repositories_path do %>
        <span class="hidden-xs">Repositories</span>
        <%= fa_icon icon_repositories %>
      <% end %>
    </li>
    <li>
      <%= link_to members_path do %>
        <span class="hidden-xs">Members</span>
        <%= fa_icon icon_members %>
      <% end %>
    </li>
    <li>
      <%= link_to groups_path do %>
        <span class="hidden-xs">Groups</span>
        <%= fa_icon icon_groups %>
      <% end %>
    </li>
  </ul>
  <% comment do %>
  <ul class="nav navmenu-nav sidebar-footer">
    <li>
      <%= link_to "#" do %>
        <span class="hidden-xs"> </span>
        <%= fa_icon icon_shrink_sidebar, data: { toggle: 'sidebar'} %>
      <% end %>
    </li>
  </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bitbucket Browser" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bitbucket Browser" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/sidebar' %>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bitbucket Browser" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bitbucket Browser" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/members/index.html.erb
<h3>Members</h3>

<div class="panel panel-default">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Full Name</th>
        <th>Username</th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.name, member_path(member.username) %></td>
        <td><%= member.username %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/members/show.html.erb
<h3><%= member_icon %> <%= @member.name %></h3>
<p>Username: <%= @member.username %></p>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Groups</h3>
  </div>
  <table class="table table-striped">
    <% comment do %>
    <thead>
      <tr>
        <th>Groups</th>
      </tr>
    </thead>
    <% end %>
    <tbody>
      <% @member.groups.sort{ |a,b| a.name <=> b.name }.each do |group| %>
      <tr>
        <td><%= link_to group.name, group_path(group.slug) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Repositories</h3>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Permission</th>
      </tr>
    </thead>
    <tbody>
      <% @member.member_permissions.sort{ |a,b| a.repository.name <=> b.repository.name }.each do |perm| %>
      <tr>
        <td><%= link_to perm.repository.name, repository_path(perm.repository.slug) %></td>
        <td width="30%"><%= perm.permission %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/repositories/index.html.erb
<h3>Repositories</h3>

<div class="panel panel-default">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= sort_link_to 'Name', repositories_path, 'name' %></th>
        <th><%= sort_link_to 'Last Updated', repositories_path, 'date' %></th>
      </tr>
    </thead>
    <tbody>
      <% @repositories.each do |repo| %>
      <tr>
        <td><%= link_to repo.name, repository_path(repo.slug) %></td>
        <td><%= repo.updated_at %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/repositories/show.html.erb
<h3><%= repository_icon %> <%= @repo.name %></h3>
<p><%= link_to @repo.url, @repo.url, target: '_blank' %></p>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Groups</h3>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Permission</th>
      </tr>
    </thead>
    <tbody>
      <% @repo.group_permissions.sort{ |a,b| a.group.name <=> b.group.name }.each do |perm| %>
      <tr>
        <td><%= link_to perm.group.name, group_path(perm.group.slug) %></td>
        <td width="30%"><%= perm.permission %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% unless @repo.member_permissions.empty? %>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Members</h3>
  </div>  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Permission</th>
      </tr>
    </thead>
    <tbody>
      <% @repo.member_permissions.sort{ |a,b| a.member.name <=> b.member.name }.each do |perm| %>
      <tr>
        <td><%= link_to perm.member.name, member_path(perm.member.username) %></td>
        <td width="30%"><%= perm.permission %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/stats/index.html.erb
<h3>Account Statistics</h3>
<div class="container-fluid">
  <div class="row">
    <div class="panel panel-primary stat-panel">
      <div class="panel-body">
        <%= repository_icon class: 'fa-4x stat-icon' %>
        <div class="stat-text">
          <p class="stat-number"><%= @repo_count %></p>
          <p class="stat-title">Repositories</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="panel panel-primary stat-panel">
      <div class="panel-body">
        <%= member_icon class: 'fa-4x stat-icon' %>
        <div class="stat-text">
          <p class="stat-number"><%= @member_count %></p>
          <p class="stat-title">Members</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="panel panel-primary stat-panel">
      <div class="panel-body">
        <%= group_icon class: 'fa-4x stat-icon' %>
        <div class="stat-text">
          <p class="stat-number"><%= @group_count %></p>
          <p class="stat-title">Groups</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>